In [1]:
import numpy as np
import pandas as pd
from PCA import PCA

In [2]:
ejemplo = PCA()
matriz = pd.DataFrame([[2, 0, 0, 0], [0, 2, 0, 0], [0, 0, 2, 0], [0, 0, 0, 2]])
ejemplo.train(matriz)

In [3]:
ejemplo.matrix

array([[ 1.        , -0.33333333, -0.33333333, -0.33333333],
       [-0.33333333,  1.        , -0.33333333, -0.33333333],
       [-0.33333333, -0.33333333,  1.        , -0.33333333],
       [-0.33333333, -0.33333333, -0.33333333,  1.        ]])

In [5]:
ejemplo.components

array([[ 0.8660254 , -0.5       , -0.21575849,  0.08864522],
       [-0.28867513, -0.5       ,  0.83906078, -0.3447314 ],
       [-0.28867513, -0.5       , -0.14556019, -0.52022854],
       [-0.28867513, -0.5       , -0.47774211,  0.77631472]])

In [6]:
ejemplo.values

array([1.33333333e+00, 5.55111512e-17, 1.33333333e+00, 1.33333333e+00])